코드 리팩토링 및 필터 추가
Gyumong/StudyPot pull request #13
Opened 2021-04-27 11:50 UTC by leo0842

리팩토링: autowired 제거
필터: 헤더의 JWT를 파싱하여 클레임으로 변환

2021-04-27 12:56 UTC, bum752 requested changes

2021-04-27 12:56 UTC, bum752 commented on back/src/main/java/com/studypot/back/filters/JwtAuthenticationFilter.java
> +    String token = request.getHeader("Authorization");
`"Authorization"` 같은 정적인 문자열들은 별도로 관리해보는건 어떨까요

2021-04-27 12:56 UTC, bum752 commented on back/src/main/java/com/studypot/back/filters/JwtAuthenticationFilter.java
> +    if (authentication != null) {
필터 이후 컨트롤러~에서는 사용자 정보를 확인하기 위해 어떻게 해야하나요?

2021-04-27 12:56 UTC, bum752 commented on back/src/main/java/com/studypot/back/WebConfigurerImpl.java
> +    Filter filter = new JwtAuthenticationFilter(authenticationManager(), jwtUtil());
필터를 빈에 등록해 스프링이 관리하도록 하는건 어떨까요?

2021-04-27 12:56 UTC, bum752 commented on back/src/main/java/com/studypot/back/utils/JwtUtil.java
> +    return parser.parseClaimsJws(token).getBody();
서명키가 다를 때에 대한 예외처리는 어떻게 하나요?

2021-04-27 12:56 UTC, bum752 commented on back/src/main/java/com/studypot/back/interfaces/SessionController.java
> +  public SessionController(UserService userService, JwtUtil jwtUtil) {
`jwtUtil` 객체는 어디서 생성되어 주입되나요?

2021-04-27 12:56 UTC, bum752 commented on back/src/main/java/com/studypot/back/filters/JwtAuthenticationFilter.java
> +    Authentication authentication = new UsernamePasswordAuthenticationToken(claims, null);
`UsernamePasswordAuthenticationToken` 생성자의 null인 부분이 credentials 인가요?
credentials 가 null 일 때 예상되는 상황이나 문제가 따로 있을까요?

2021-04-27 13:14 UTC, leo0842 commented on back/src/main/java/com/studypot/back/filters/JwtAuthenticationFilter.java
> +    if (authentication != null) {
필터링된 Authentication 객체를 컨트롤러에서 받고 이 객체에서 페이로드의 정보들을 받아옵니다!

2021-04-27 13:15 UTC, leo0842 commented on back/src/main/java/com/studypot/back/utils/JwtUtil.java
> +    return parser.parseClaimsJws(token).getBody();
예외처리 만들어야 하겠습니다.

2021-04-27 13:17 UTC, leo0842 commented on back/src/main/java/com/studypot/back/interfaces/SessionController.java
> +  public SessionController(UserService userService, JwtUtil jwtUtil) {
webConfigurerImpl에서 생성됩니다!

2021-04-27 13:19 UTC, leo0842 commented on back/src/main/java/com/studypot/back/filters/JwtAuthenticationFilter.java
> +    Authentication authentication = new UsernamePasswordAuthenticationToken(claims, null);
넵 credentials 입니다. 아직 credentials까지 생각은 못해봤습니다.

2021-04-27 13:20 UTC, leo0842 commented on back/src/main/java/com/studypot/back/filters/JwtAuthenticationFilter.java
> +    String token = request.getHeader("Authorization");
별도로 관리한다는 말은 클래스 내부에 로컬 변수로 관리한다는 것인가요?

2021-04-27 13:21 UTC, leo0842 commented on back/src/main/java/com/studypot/back/WebConfigurerImpl.java
> +    Filter filter = new JwtAuthenticationFilter(authenticationManager(), jwtUtil());
이렇게 생성자를 이용하는 것은 무리가 있는 건가요?

2021-04-27 14:39 UTC, bum752 commented on back/src/main/java/com/studypot/back/interfaces/SessionController.java
> +  public SessionController(UserService userService, JwtUtil jwtUtil) {
WebConfigurerImpl 에서 빈으로 등록하는 이유가 있을까요?

`JwtUtil` 자체를 `@Component` 어노테이션을 이용해 빈으로 등록할 수 있습니다
생성자의 파라미터에 `@Value`를 사용해보세요

```java
@Component
pulic class JwtUtil {

  // ...

  public JwtUtil(@Value("${jwt.secret}") String secretKey) {
    this.key = Keys.hmacShaKeyFor(secretKey.getBytes());
  }

  // ...
}
```

2021-04-27 14:40 UTC, bum752 commented on back/src/main/java/com/studypot/back/WebConfigurerImpl.java
> +    Filter filter = new JwtAuthenticationFilter(authenticationManager(), jwtUtil());
상관없지만 프레임워크가 관리해주도록 위임하는게 좋을거 같습니다

2021-04-27 23:52 UTC, bum752 commented on back/src/main/java/com/studypot/back/filters/JwtAuthenticationFilter.java
> +    String token = request.getHeader("Authorization");
[스프링 Constant Field Values](https://docs.spring.io/spring-boot/docs/current/api/constant-values.html) 참고

2021-04-28 05:44 UTC, leo0842 commented on back/src/main/java/com/studypot/back/interfaces/SessionController.java
> +  public SessionController(UserService userService, JwtUtil jwtUtil) {
이 방법이 더욱 직관적이기때문인가요?

2021-04-28 08:49 UTC, merged