스터디 생성 API
Gyumong/StudyPot pull request #57
Opened 2021-06-12 07:05 UTC by leo0842

1. Controller
- thumbnail image를 포함하기때문에 multipart/form-data로 데이터를 받음

2. Service
- 스터디 객체를 먼저 생성한 뒤 Join 관계의 주인 엔터티에 객체를 생성

3. Dto
- Dto에 스터디를 생성하는 메소드를 만들어 Service에서 getter 접근을 최소화

4. User
- 사용자가 참여한 스터디 조회를 Entity 내부에서 메소드로 구현하고 네이밍을 직관적으로 바꿈

2021-06-16 00:25 UTC, bum752 requested changes
전체적으로 포매팅이 제각각이네요

어떤 메소드는 시작과 끝에 공백 라인이 있고 어떤 메소드는 없네요
파일의 끝에도 공백 라인이 있고 없고가 달라요

**포매팅은 항상 신경쓸 것**을 추천합니다

2021-06-16 00:25 UTC, bum752 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +    }
이렇게 하면 변수에 값은 들어가겠지만 초기화되지 않은 변수가 선언되는 걸 개인적으로는 선호하지 않는데요
수정해볼 수 있을까요??
문제없다고 생각하시면 패스해도 될듯합니다

2021-06-16 00:25 UTC, bum752 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +    updateCategories(studyCreateRequestDto.getCategories(), savedStudy);
저장을 위해 유저를 꼭 조회해야할까요??

2021-06-16 00:25 UTC, bum752 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +  private void updateCategories(List<CategoryName> categories, Study study) {
업데이트 맞나요?? 계속 추가만 될 것 같아보이는데요
동일한 카테고리로 메소드가 반복적으로 호출되면 중복은 없나요?

2021-06-16 00:25 UTC, bum752 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +    return UUID.randomUUID().toString().concat(fileNameExtension(name));
저는 파일명에 꼭 확장자를 붙여주지는 않아도 된다고 생각하는데
필요한 이유가 있을까요??

2021-06-16 00:25 UTC, bum752 commented on back/src/main/java/com/studypot/back/dto/study/StudyCreateRequestDto.java
> +  public Study studyBuilder(Long userId, String thumbnailUrl) {
메소드 실행 결과는 Study 인데 `studyBuilder` 라는 이름이 어울리지 않는거 같아요

2021-06-16 03:47 UTC, leo0842 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +    }
넵 수정하겠습니다!

2021-06-16 03:53 UTC, leo0842 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +    updateCategories(studyCreateRequestDto.getCategories(), savedStudy);
유저를 조회하지 않고 UserId로 유저 객체를 받아오는 방법이 있나요??
생각해보니 굳이 유저로 조인을 안걸고 userId를 저장하는 방법이 나중에 studyMember를 조회할 때도 쿼리가 덜 나갈 것 같습니다. 해당 entity를 수정하겠습니다.

2021-06-16 04:02 UTC, leo0842 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +  private void updateCategories(List<CategoryName> categories, Study study) {
네이밍을 잘못한 것 같습니다.수정하겠습니다.

2021-06-16 04:03 UTC, leo0842 commented on back/src/main/java/com/studypot/back/dto/study/StudyCreateRequestDto.java
> +  public Study studyBuilder(Long userId, String thumbnailUrl) {
studyObjectResponse로 바꾸겠습니다.

2021-06-16 04:06 UTC, leo0842 commented on back/src/main/java/com/studypot/back/dto/study/StudyCreateRequestDto.java
> +  public Study studyBuilder(Long userId, String thumbnailUrl) {
studyConstructor 는 어떨까요

2021-06-16 04:07 UTC, bum752 commented on back/src/main/java/com/studypot/back/dto/study/StudyCreateRequestDto.java
> +  public Study studyBuilder(Long userId, String thumbnailUrl) {
`convertToStudy` 정도로 해도될거같아요

2021-06-16 04:24 UTC, leo0842 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +    return UUID.randomUUID().toString().concat(fileNameExtension(name));
혹시 생각지못한 파일이 들어왔을 때 확인하면 좋을 것 같아서요! 스트링 크기가 영향을 줄 만한 정도가 아니기때문에 굳이 버릴 필요는 없다고 생각했습니다.

2021-06-20 14:06 UTC, bum752 requested changes

2021-06-20 14:06 UTC, bum752 commented on back/src/main/java/com/studypot/back/applications/StudyService.java
> +    return UUID.randomUUID().toString().concat(fileNameExtension(name));
`fileNameExtension()` 에서 예외를 발생하지만 처리가 안됩니다.
파일명에 확장자가 없는 이미지가 업로드 될 경우에는 실패하는데 확장자를 붙여두고 싶다면 핸들링을 더 하는게 좋을거 같아요

2021-06-20 14:06 UTC, bum752 commented on back/src/main/java/com/studypot/back/domain/Study.java
> +  private final List<StudyMember> members = new ArrayList<>();
`final` 변수인 이유가 있나요?

2021-06-20 14:06 UTC, bum752 commented on back/src/test/java/com/studypot/back/applications/StudyServiceTest.java
> +  public void addStudy() throws IOException {
테스트 이름은 항상 의미있게 지어주세요
영문 메소드명으로 어렵다면 한글 메소드명이나 `@DisplayName` 같은 junit 어노테이션을 사용하면 좋을거 같아요

2021-06-21 15:07 UTC, merged